USE uargflow;

DROP TABLE IF EXISTS GESTOR_FORMULARIOS;

CREATE TABLE GESTOR_FORMULARIOS(
	idusuario INT NOT NULL,
	limite SMALLINT DEFAULT -1,
	libertad BIT NOT NULL,
	FOREIGN KEY (idusuario) REFERENCES USUARIO(idusuario)
);